# Dev environment values. No secrets here: the DB password is generated by
# Terraform (random_password) and written only to Key Vault + remote state.
environment = "dev"
prefix      = "healthcare"
location    = "centralindia"

# Remote state backend (also supplied via -backend-config in CI).
backend_resource_group  = "rg-terraform"
backend_storage_account = "tfstatehealthcare"
backend_container       = "tfstate"
backend_key             = "healthcare-azure-dev.tfstate"

resource_group_name  = "rg-healthcare-dev-tf"
vnet_name            = "healthcare-vnet-dev"
vnet_cidr            = "10.20.0.0/16"
private_subnet_cidr  = "10.20.1.0/24"
public_subnet_cidr   = "10.20.2.0/24"
postgres_subnet_cidr = "10.20.3.0/24"
availability_zones   = ["1", "2", "3"]

acr_name = "healthcareacrdevtf"
acr_sku  = "Standard"

keyvault_name        = "hc-kv-dev-733833"
tenant_id            = "a90a3e51-3c2e-4181-9600-bc0e180533e9"
keyvault_secret_name = "database-url"

postgres_server_name   = "hc-pg-dev-733833"
postgres_admin_user    = "pgadmin"
postgres_sku           = "B_Standard_B1ms"
postgres_storage_gb    = 32
postgres_database_name = "healthcare"

aks_cluster_name = "aks-healthcare-dev"
aks_node_count   = 1
aks_node_vm_size = "Standard_D2s_v3"
aks_min_count    = 1
aks_max_count    = 3
